{% set name = "voms" %}
{% set version = "2.1.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/italiangrid/{{ name }}/archive/v{{ version|replace('rc', '-rc') }}.tar.gz
  sha256: 4908526865889b7e8af6ff0264cf7f05a42834d71dfd9b01c2318937e826229d
  patches:
    - patches/0001-HACK-Add-NI_MAXHOST-and-NI_MAXSERV-for-macOS.patch
    - patches/0002-Only-set-authority-key-identified-field-if-the-publi.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - automake
    - libtool
    - make
    - pkg-config
    - gsoap  # [build_platform != target_platform]
  host:
    - expat
    - gsoap
    - openssl
    - zlib
  run_constrained:
    # Mark voms as conflicting with voms-clients
    - voms-clients ==9999999

test:
  commands:
    - voms-proxy-destroy --help
    - voms-proxy-fake --help
    - voms-proxy-info --help
    - voms-proxy-init --help
    - voms-proxy-list --help
    - which voms-verify

about:
  home: http://italiangrid.github.io/voms/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Virtual Organisation Membership Service (C/C++ clients and APIs)'

  description: |
     The Virtual Organization Membership Service (VOMS) is an attribute
     authority which serves as central repository for VO user authorization
     information, providing support for sorting users into group hierarchies,
     keeping track of their roles and other attributes in order to issue
     trusted attribute certificates and SAML assertions used in the Grid
     environment for authorization purposes.
  doc_url: https://italiangrid.github.io/voms/documentation.html
  dev_url: https://github.com/italiangrid/voms

extra:
  recipe-maintainers:
    - chrisburr
